name: PHPUnit

on:
  push:
    branches:
      - main
      - 3.x
  pull_request:
  schedule:
    - cron: '0 14 * * 3' # Run Wednesdays at 2pm EST

jobs:
  php-tests:
    strategy:
      matrix:
        dependency-version: [ stable, lowest ]
        os: [ ubuntu-latest, windows-latest ]
        laravel: [ 11.*, 12.* ]
        php: [ 8.3, 8.4 ]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    name: "${{ matrix.php }} / ${{ matrix.laravel }} (${{ matrix.dependency-version }})"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, bcmath, intl, iconv, fileinfo
          tools: composer:v2
      
      - name: Register composer cache directory
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v4
        if: ${{ steps.composer-cache.outputs.dir != '' }}
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: |
          composer require --no-interaction --prefer-dist --update-with-all-dependencies --prefer-${{ matrix.dependency-version }} "illuminate/support:${{ matrix.laravel }}"

      - name: Execute tests
        run: vendor/bin/phpunit
